### ISSUE TITLE
issue after watching data observer video

### ISSUE THREAD

**Issue by taha786** [slidenerd/BucketDrops#11]
Dear Vivz
               i hope you are doing fine please solve my this error i am stuck on that error .
my android studio version is 2.2.3 and i am using appcombat 25.1.0 and also using same version of recyclerview library that is 25.1.0

FATAL EXCEPTION: main
                                                 Process: mobileapp.com.bucketdrop, PID: 5731
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{mobileapp.com.bucketdrop/mobileapp.com.bucketdrop.ActivityMain}: java.lang.NullPointerException
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
                                                     at android.os.Handler.dispatchMessage(Handler.java:110)
                                                     at android.os.Looper.loop(Looper.java:193)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.NullPointerException
                                                     at mobileapp.com.bucketdrop.extras.Util.showViews(Util.java:15)
                                                     at mobileapp.com.bucketdrop.widgets.BucketRecyclerView.toggleViews(BucketRecyclerView.java:61)
                                                     at mobileapp.com.bucketdrop.widgets.BucketRecyclerView.access$000(BucketRecyclerView.java:21)
                                                     at mobileapp.com.bucketdrop.widgets.BucketRecyclerView$1.onChanged(BucketRecyclerView.java:27)
                                                     at mobileapp.com.bucketdrop.widgets.BucketRecyclerView.setAdapter(BucketRecyclerView.java:98)
                                                     at mobileapp.com.bucketdrop.ActivityMain.onCreate(ActivityMain.java:66)
                                                     at android.app.Activity.performCreate(Activity.java:5264)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                     at android.os.Looper.loop(Looper.java:193) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5292) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 

Regards
Taha Ahmad

**Comment by taha786** [comment]
please reply vivz

**Comment by taha786** [comment]
dear vivz 
                i am waiting for your response please help me to solve the above  error
